# Generated by Django 3.2.15 on 2022-12-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basicData', '0009_auto_20221226_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorsatnGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[(1, 'فروردین'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهربور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], max_length=20)),
                ('year', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basicData.barache')),
                ('tgroups', models.ManyToManyField(related_name='targetgroups', to='basicData.GoodsSubGroup')),
            ],
            options={
                'verbose_name': 'تعریف تارگت شعبه',
                'verbose_name_plural': 'تعریف تارگت های شعب',
            },
        ),
    ]
