# Generated by Django 3.2.15 on 2022-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porsant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porsatngroup',
            name='qnty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
