# Generated by Django 3.2.15 on 2022-12-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicData', '0009_auto_20221226_1905'),
        ('porsant', '0002_porsatngroup_qnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porsatngroup',
            name='month',
            field=models.CharField(choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'آبان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=20),
        ),
        migrations.CreateModel(
            name='SalerTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'فروردین'), ('2', 'اردیبهشت'), ('3', 'خرداد'), ('4', 'تیر'), ('5', 'مرداد'), ('6', 'شهریور'), ('7', 'مهر'), ('8', 'آبان'), ('9', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=20)),
                ('year', models.IntegerField()),
                ('qnty', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basicData.barache')),
                ('tgroups', models.ManyToManyField(to='basicData.GoodsSubGroup')),
            ],
            options={
                'verbose_name': 'تعریف فروشنده',
                'verbose_name_plural': 'تارگت فروشندگان',
            },
        ),
    ]
