# Generated by Django 3.2.15 on 2022-12-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porsant', '0004_salertargets_saler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salertargets',
            options={'verbose_name': 'تارگت فروشنده', 'verbose_name_plural': 'تارگت فروشندگان'},
        ),
        migrations.RemoveField(
            model_name='salertargets',
            name='center',
        ),
    ]
