# Generated by Django 3.2.15 on 2022-12-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porsant', '0005_auto_20221226_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='salertargets',
            name='accept',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
