# Generated by Django 3.2.15 on 2022-12-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDivideGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'گروه جدا کننده',
                'verbose_name_plural': 'جداکنندگان',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoodsMainGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'گروه اصلی محصول',
                'verbose_name_plural': 'گروه های اصلی',
            },
        ),
        migrations.CreateModel(
            name='GoodsSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'زیر گروه محصول',
                'verbose_name_plural': 'زیر گروه محصولات',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=225)),
                ('inBox', models.IntegerField()),
                ('dgroup', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basicData.goodsdividegroup')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basicData.goodssubgroup')),
            ],
        ),
    ]
