# Generated by Django 3.2.15 on 2022-12-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': '4-نام محصول', 'verbose_name_plural': '4-نام محصولات'},
        ),
        migrations.AlterModelOptions(
            name='goodsdividegroup',
            options={'managed': True, 'verbose_name': '3-گروه جدا کننده', 'verbose_name_plural': '3-جداکنندگان'},
        ),
        migrations.AlterModelOptions(
            name='goodsmaingroup',
            options={'verbose_name': '1-گروه اصلی محصول', 'verbose_name_plural': '1-گروه های اصلی'},
        ),
        migrations.AlterModelOptions(
            name='goodssubgroup',
            options={'verbose_name': '2-زیر گروه محصول', 'verbose_name_plural': '2-زیر گروه محصولات'},
        ),
        migrations.AddField(
            model_name='goodssubgroup',
            name='mainGroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='basicData.goodsmaingroup'),
            preserve_default=False,
        ),
    ]
