# Generated by Django 3.2.15 on 2022-12-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicData', '0008_auto_20221225_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barache',
            options={'verbose_name': 'مرکز فروش', 'verbose_name_plural': 'مراکز فروش'},
        ),
        migrations.AlterModelOptions(
            name='costumersactivity',
            options={'verbose_name': 'فعالیت مشتری', 'verbose_name_plural': 'فعالیتها'},
        ),
        migrations.AlterModelOptions(
            name='dc',
            options={'verbose_name': 'مرکز اصلی', 'verbose_name_plural': 'مراکز اصلی'},
        ),
        migrations.AlterModelOptions(
            name='districtmanager',
            options={'verbose_name': 'مدیر منطقه', 'verbose_name_plural': 'مدیران مناطق'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'نام محصول', 'verbose_name_plural': 'نام محصولات'},
        ),
        migrations.AlterModelOptions(
            name='goodsdividegroup',
            options={'managed': True, 'verbose_name': 'گروه جدا کننده', 'verbose_name_plural': 'جداکنندگان'},
        ),
        migrations.AlterModelOptions(
            name='goodsmaingroup',
            options={'verbose_name': 'گروه اصلی محصول', 'verbose_name_plural': 'گروه های اصلی'},
        ),
        migrations.AlterModelOptions(
            name='goodssubgroup',
            options={'verbose_name': 'زیر گروه محصول', 'verbose_name_plural': 'زیر گروه محصولات'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'مدیر شعبه', 'verbose_name_plural': 'مدیریت شعب'},
        ),
        migrations.AlterModelOptions(
            name='saleline',
            options={'verbose_name': 'لاین فروش', 'verbose_name_plural': 'لاین های فروش'},
        ),
        migrations.AlterModelOptions(
            name='superviseur',
            options={'verbose_name': 'سرپرست', 'verbose_name_plural': 'سرپرستان'},
        ),
    ]
